# Generated by Django 5.1.1 on 2024-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('2731', 'Las palmas 2731'), ('2779', 'Las palmas 2779'), ('2838', 'Las palmas 2838'), ('2850', 'Las palmas 2850'), ('2856', 'Las palmas 2856'), ('2876', 'Las palmas 2876'), ('1123', 'Corrales 1123'), ('970', 'Ramire 970')], default='Perro', max_length=8)),
                ('piso', models.SmallIntegerField()),
                ('departamento', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
