# Generated by Django 5.1.1 on 2024-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='direccion',
            field=models.CharField(choices=[('Las palmas 2731', 'Las palmas 2731'), ('Las palmas 2779', 'Las palmas 2779'), ('Las palmas 2838', 'Las palmas 2838'), ('Las palmas 2850', 'Las palmas 2850'), ('Las palmas 2856', 'Las palmas 2856'), ('Las palmas 2876', 'Las palmas 2876'), ('Corrales 1123', 'Corrales 1123'), ('Ramirez 970', 'Ramirez 970')], default='Perro', max_length=100),
        ),
    ]
