# Generated by Django 5.1.1 on 2024-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jade', '0002_alter_ventas_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='cantidad',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
