# Generated by Django 5.1.1 on 2024-10-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jade', '0003_rename_cantidad_ventas_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
