# Generated by Django 5.1.1 on 2024-10-06 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jade', '0005_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
