# Generated by Django 5.1.1 on 2024-10-10 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jade', '0006_ventas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='direccion_personalizada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='direccion',
            field=models.CharField(choices=[('Las palmas 2731', 'Las palmas 2731'), ('Las palmas 2779', 'Las palmas 2779'), ('Las palmas 2838', 'Las palmas 2838'), ('Las palmas 2850', 'Las palmas 2850'), ('Las palmas 2856', 'Las palmas 2856'), ('Las palmas 2876', 'Las palmas 2876'), ('Fournier 2901', 'Fournier 2901'), ('Corrales 1123', 'Corrales 1123'), ('Ramirez 970', 'Ramirez 970'), ('Otros', 'Otros')], default='Perro', max_length=100),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
